#!/usr/bin/env python3
"""Pull sessions/events/WORKS out of index.html into reusable files in ~/s2u-data
(private, outside the public repo): content-bank.md, works.csv, partners.csv.
Re-run after every site update."""
import csv, os, re, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.expanduser("~/s2u-data")
os.makedirs(OUT, exist_ok=True)
html = open(os.path.join(ROOT, "index.html"), encoding="utf-8").read()


def block(name):
    m = re.search(rf"\b(?:const|let)\s+{name}\s*=\s*\[", html)
    start, depth, i = m.end() - 1, 0, m.end() - 1
    while True:
        c = html[i]
        depth += c == "["
        depth -= c == "]"
        if depth == 0:
            return html[start : i + 1]
        i += 1


def objs(text):
    out, depth, cur = [], 0, None
    quote = None
    for i, c in enumerate(text):
        if quote:
            if c == quote and text[i - 1] != "\\":
                quote = None
            continue
        if c in "'\"`":
            quote = c
        elif c == "{":
            if depth == 0:
                cur = i
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                out.append(text[cur : i + 1])
    return out


def fields(o):
    d = {}
    for m in re.finditer(r"""(\w+):\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)"|(\d+))""", o):
        d[m.group(1)] = next(g for g in m.groups()[1:] if g is not None).replace("\\'", "'")
    return d


sessions = [fields(o) for o in objs(block("sessions"))]
events = [fields(o) for o in objs(block("events"))]
works = [fields(o) for o in objs(block("WORKS"))]

with open(os.path.join(OUT, "works.csv"), "w", newline="", encoding="utf-8-sig") as f:
    w = csv.writer(f)
    w.writerow(["date", "category", "title", "partners", "place", "summary", "instagram", "video"])
    for x in sorted(works, key=lambda x: x.get("date", ""), reverse=True):
        w.writerow([x.get("date"), x.get("cat"), x.get("t"), x.get("w"), x.get("place"), x.get("d"), x.get("ig"), x.get("v")])

partners = collections.Counter()
for x in works:
    for p in re.split(r"\s*[·×,]\s*", x.get("w", "")):
        if p.strip():
            partners[p.strip()] += 1
with open(os.path.join(OUT, "partners.csv"), "w", newline="", encoding="utf-8-sig") as f:
    w = csv.writer(f)
    w.writerow(["partner", "collaborations"])
    for p, n in partners.most_common():
        w.writerow([p, n])

lines = ["# S2:U content bank", "", "_Generated by scripts/export-content.py — do not edit by hand._", "", "## Programs"]
for s in sessions:
    lines.append(f"- **{s.get('name')}** ({s.get('catLabel')}) — {s.get('nick')} · {s.get('day')} · {s.get('duration')} · max {s.get('cap')}\n  {s.get('desc')}")
lines += ["", "## Events"]
for e in events:
    lines.append(f"- {e.get('date')} **{e.get('title')}** [{e.get('cat')}] with {e.get('with')} — {e.get('participants')} people\n  {e.get('desc')}")
lines += ["", "## Archive (WORKS)"]
for x in sorted(works, key=lambda x: x.get("date", ""), reverse=True):
    lines.append(f"- {x.get('date')} **{x.get('t')}** [{x.get('cat')}] — {x.get('w')}\n  {x.get('long') or x.get('d')}\n  {x.get('ig','')}")
open(os.path.join(OUT, "content-bank.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"sessions={len(sessions)} events={len(events)} works={len(works)} partners={len(partners)} -> {OUT}")
